---
  api_key:
    description: "PowerDNS API Key"
    type: "string"
    secret: true
    required: true
  api_url:
    description: "URL to PowerDNS API."
    type: "string"
    secret: false
    required: true
